sudo-false
language: 
  - cpp
compiler: 
  - gcc
addons:
  apt:
    sources:
      -ubuntu-toolchain-r-test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq
install:
  - apt-get update
  - apt-get install g++-4.8
  - update-alternatives --install /usr/bin/g++ g++ /user/bin/g++-4.8 90
  - update-alternatives --install /usr/bin/gcc gcc /user/bin/gcc-4.8 90
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make
  - ./runTests
