language: 
  - cpp
compiler: 
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make
  - ./runTests
